### PR TITLE
Remove PyBlock temp techs

### PR DESCRIPTION
**Pull request by protocol-1903**
Removes the temp techs for pyblock so that it can load properly without user modification

### CODE REVIEW

**Comment by notnotmelon** [comment]
Two issues I see before this could be merged:

- We should not be commenting this code. Better to simply delete it as I doubt it will ever be used again.
- Make sure to update the changelog for every PR

**Comment by protocol-1903** [comment]
Well should just that segment be deleted, or the whole temp techs section?

**Comment by notnotmelon** [comment]
Merged! Thank you and best of luck with pyblock.

**Comment by protocol-1903** [comment]
o7

**Pull request merged**
